steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "<REGION>-docker.pkg.dev/<PROJECT_ID>/<ARTIFACT_REGISTRY_REPO>/<WORKER_IMAGE_NAME>:latest",
        "-f",
        "Dockerfile.worker",
        ".",
      ]
images:
  - <REGION>-docker.pkg.dev/<PROJECT_ID>/<ARTIFACT_REGISTRY_REPO>/<WORKER_IMAGE_NAME>:latest
